export interface matrimonioRequest {
    scIdTipoSacramento: number,
    scNumeroPartida: string,
    peNombreEsposo: string,
    peNombreEsposa: string,
    peEdadEsposo: number,
    peEdadEsposa: number,
    peFechaNacimientoEsposo: Date,
    peFechaNacimientoEsposa: Date,
    peIdTipoDocumentoEsposo: number,
    peIdTipoDocumentoEsposa: number,
    peNumeroDocumentoEsposo: string,
    peNumeroDocumentoEsposa: string,
    peSexoIdEsposo: number,
    peSexoIdEsposa: number,
    peDireccionEsposo: string,
    peDireccionEsposa: string,
    scPadreEsposo: string,
    scPadreEsposa: string,
    scMadreEsposo: string,
    scMadreEsposa: string,
    scTestigo1: string,
    scTestigo2: string,
    scParrocoId: number,
    scFechaSacramento: Date,
    scObservaciones: string
}